name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test: Python 3.11"
            python: "3.11"
            tox: "3.11"
          - name: "Test: Python 3.12"
            python: "3.12"
            tox: "3.12"
          - name: "Test: Python 3.13"
            python: "3.13"
            tox: "3.13"
            coverage: true
          - name: "Lint: pyright"
            python: "3.13"
            tox: "pyright"
          - name: "Lint: ruff lint"
            python: "3.13"
            tox: "ruff-lint"
          - name: "Lint: ruff format"
            python: "3.13"
            tox: "ruff-format"

    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    container: ghcr.io/mopidy/ci:latest

    steps:
      - uses: actions/checkout@v4
      - name: Fix home dir permissions to enable pip caching
        run: chown -R root /github/home
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - run: python -m pip install tox
      - run: python -m tox -e ${{ matrix.tox }}
        if: ${{ ! matrix.coverage }}
      - run: python -m tox -e ${{ matrix.tox }} -- --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.coverage }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}